# Generated by Django 3.0.3 on 2020-02-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='body',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x00000001FE895CF8>'),
        ),
    ]
